---
define: &sampling 30
define: &classes 40

outdir: 'mlp_30p'
data_hyperparams:
  pc_rootdir: '../data/ModelNet40_30p'
  classes: *classes
  pretransforms:
    norm: True
    sampling: *sampling
  transforms: null
  torch_dataloader:
    batch_size: 64
    shuffle: True
    num_workers: 4

model_type: "mlp_basic"

model_hyperparams:
  input_dim: 90
  layers: [1024, 512, 256, 128, 64]
  activ: "relu"
  # dropout_rate: 0.5
  output_dim: *classes

training_hyperparams:
  lr: 0.001
  lr_step_start: 50
  lr_step_interval: 50
  epochs: 200
  loss: "ce"
  weight_decay: 0.000001
  # clip_grad: 5
  early_stopping: 20
