---
define: &sampling 1000
define: &classes 40

outdir: 'deepsinv_mlp_1000p'
data_hyperparams:
  pc_rootdir: "../data/ModelNet40_1000p"
  classes: *classes
  pretransforms:
    norm: True
    sampling: *sampling
  transforms: null
  torch_dataloader:
    batch_size: 64
    shuffle: True
    num_workers: 12

teacher: "trained_deepsets/deepsinv_1000p_zaheer/"
model_type: "basic"
model_hyperparams:
  input_dim: 3000
  layers: [512, 512, 256, 256]
  activ: "relu"
  output_dim: *classes


distill_hyperparams:
  lr: 0.001
  epochs: 1000
  early_stopping: 20
  alpha: 0
  temp: 4
