---
define: &sampling 1000
define: &classes 40

outdir: 'dgcnn_1000p'
data_hyperparams:
  pc_rootdir: "../data/ModelNet40_1000p"
  classes: *classes
  pretransforms:
    norm: True
    sampling: *sampling
  transforms: null
  dataloader_type: "normal"
  torch_dataloader:
    batch_size: 64
    shuffle: True
    num_workers: 8

model_type: "dgcnn"

model_hyperparams:
  aggr: "max"
  k: 20
  output_dim: *classes

training_hyperparams:
  lr: 0.001
  lr_step_start: 100
  lr_step_interval: 100
  epochs: 1000
  weight_decay: 0.0000001
  loss: "ce"
  # clip_grad: 5
  early_stopping: 10
