---
define: &sampling 1000
define: &classes 40

storage: 'mlp'
study_name: 'modelnet_1000p'

data_hyperparams:
  pc_rootdir: '../data/ModelNet40_1000p'
  classes: *classes
  pretransforms:
    norm: True
    sampling: *sampling
  transforms: null
  torch_dataloader:
    batch_size: [64, 128, 256, 512, 1024]
    shuffle: True
    num_workers: 8

model_type: "mlp_reged"

model_hyperparams:
  input_dim: 3000
  nlayers: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  nnodes: [128, 256, 512, 1024]
  activ: ["relu", "tanh", "leaky_relu"]
  dropout_rate: [0.0, 0.5]
  output_dim: *classes

training_hyperparams:
  lr: [0.00001, 0.001]
  epochs: 200
  weight_decay: [0.00001, 0.001]
  early_stopping: 30
