name: distinv
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - attr=2.5.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-runtime=12.1.0
  - cycler=0.12.1
  - dbus=1.13.6
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.6
  - jack=1.9.22
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.1.2
  - libcups=2.3.3
  - libcurand=10.3.4.101
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgomp=13.2.0
  - libgpg-error=1.47
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsndfile=1.2.2
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.3
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.96
  - numpy=1.26.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.4
  - packaging=23.2
  - pandas=2.1.4
  - pcre2=10.42
  - pillow=9.4.0
  - pip=23.3.2
  - pixman=0.42.2
  - plotly=5.18.0
  - ply=3.11
  - psutil=5.9.7
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pyg=2.4.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tenacity=8.2.3
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.1.2
  - torchinfo=1.8.0
  - torchtriton=2.1.0
  - torchvision=0.16.2
  - tornado=6.3.3
  - tqdm=4.66.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - wheel=0.42.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
