---
outdir: 'deepsets_paper_1000p_notrans'
data_hyperparams:
  train_trans:
    sampling: 1000
    norm: True
    rotation: False
    noise: False
    tensor: True
  valid_trans:
    sampling: 1000
    norm: True
    rotation: False
    noise: False
    tensor: True
  pc_rootdir: "../data/ModelNet40"
  torch_dataloader:
    batch_size: 64
    shuffle: True

deepsets_type: "equivariant"

model_hyperparams:
  phi_layers: [256, 256, 256]
  rho_layers: [256]
  activ: "tanh"
  aggreg: "max"
  dropout: 0.5

training_hyperparams:
  lr: 0.001
  epochs: 1000
  weight_decay: 0.0000001
  clip_grad: 5
  early_stopping: 15
