#!/usr/bin/env bash
nohup python -u train.py --config configs/config_paper_100p_equivariant.yml --seed 42 --device cuda:2 > ./logs/deepsequiv_1000p_zaheer_s42 &
nohup python -u train.py --config configs/config_paper_100p_equivariant.yml --seed 121 --device cuda:2 > ./logs/deepsequiv_1000p_zaheer_s121 &
nohup python -u train.py --config configs/config_paper_100p_equivariant.yml --seed 308 --device cuda:2 > ./logs/deepsequiv_1000p_zaheer_s308 &
nohup python -u train.py --config configs/config_paper_100p_equivariant.yml --seed 240 --device cuda:3 > ./logs/deepsequiv_1000p_zaheer_s240 &
nohup python -u train.py --config configs/config_paper_100p_equivariant.yml --seed 101 --device cuda:3 > ./logs/deepsequiv_1000p_zaheer_s101 &
