#!/usr/bin/env bash

nohup python -u distill.py --config configs/config_dgcnn_to_deepsinv_1000p.yml --seed 42 --device cuda:0 > ./logs/dgcnn_to_deepsinv_T4_1000p_s42 &
nohup python -u distill.py --config configs/config_dgcnn_to_deepsinv_1000p.yml --seed 121 --device cuda:1 > ./logs/dgcnn_to_deepsinv_T4_1000p_s121 &
nohup python -u distill.py --config configs/config_dgcnn_to_deepsinv_1000p.yml --seed 308 --device cuda:2 > ./logs/dgcnn_to_deepsinv_T4_1000p_s308 &
nohup python -u distill.py --config configs/config_dgcnn_to_deepsinv_1000p.yml --seed 240 --device cuda:3 > ./logs/dgcnn_to_deepsinv_T4_1000p_s240 &
