#!/usr/bin/env bash

nohup python -u train.py --config configs/config_mlp_1000p.yml --seed 42 > ./logs/mlp_1000p_s42 &
nohup python -u train.py --config configs/config_mlp_1000p.yml --seed 121 > ./logs/mlp_1000p_s121 &
nohup python -u train.py --config configs/config_mlp_1000p.yml --seed 308 > ./logs/mlp_1000p_s308 &
nohup python -u train.py --config configs/config_mlp_1000p.yml --seed 240 > ./logs/mlp_1000p_s240 &
nohup python -u train.py --config configs/config_mlp_1000p.yml --seed 101 > ./logs/mlp_1000p_s101 &
