name: DistInv
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-runtime=12.1.0
  - cycler=0.12.1
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gmpy2=2.1.2
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.6
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcurand=10.3.4.101
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdb=6.2.32
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgomp=13.2.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnpp=12.0.2.50
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
